---
- name: "Deploy Apache container using docker"
  hosts: "{{ target_host }}"
  become: yes
  vars:
    docker_host: "unix://var/run/docker.sock"
    target_host: prod

  pre_tasks:
    - name: "Install EPEL repo"
      package:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS"

    - name: "Download pip script"
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install python-pip
      command: python2.7 /tmp/get-pip.py

    - name: "Create a symbolic link for pip"
      file:
        src: /usr/local/bin/pip
        dest: /usr/bin/pip
        state: link
        force: yes

    - name: "Install docker python"
      pip:
        name: docker-py

    - name: "Install Docker dependencies"
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      when: ansible_distribution == "CentOS"

    - name: "Add Docker repo"
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
      when: ansible_distribution == "CentOS"

    - name: "Install Docker"
      yum:
        name: docker-ce
        state: present
      when: ansible_distribution == "CentOS"

    - name: "Start and enable Docker service"
      systemd:
        name: docker
        state: started
        enabled: yes

  tasks:
    - name: "Copy website template file"
      template:
        src: index.html.j2
        dest: /home/vagrant/index.html

    - name: "Create Apache container"
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "8080:80"
        volumes:
          - /home/vagrant/index.html:/usr/local/apache2/htdocs/index.html
